name: build-images-action

permissions:
  contents: read

on:
  push:
    branches:
    - 'main'
    - 'release-*'
    tags:
    - 'capm3-v*'

jobs:
  build_mariadb:
    name: Build Mariadb container image
    if: github.repository == 'metal3-io/mariadb-image'
    uses: metal3-io/project-infra/.github/workflows/container-image-build.yml@main
    with:
      image-name: 'mariadb'
      pushImage: true
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
